# Generated by Django 4.1 on 2024-07-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0002_entidad_alter_entidadreclamo_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entidad',
        ),
    ]
